### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by rominf** [oddjobz/pynndb#12]
Since you are using Python 3.6, it's possible to add type annotations. I found confusing usage of transactions, for me it's not obvious where `txn` is an `lmdb.Txn`, and where it's `pynndb.Transaction`.

**Comment by oddjobz** [comment]
The short answer is yes, absolutely type annotations would be good, and don't use "pynndb.Transaction", this was an addition used for replication that isn't really documented. I recently added some cleaner documentation, but this is still incomplete and is for current pynndb installations .. and partially to work out how I'm going to document "the next version". 

Speaking of which, for the last couple of weeks I've been reworking the code (it's a rewrite) with a view to making it more Pythonic, self-documenting and 'ready' for the 'C' based speedups I worked on previously. It's now in a position where it's working, and I'm coding a real-world solution in parallel to iron out the niggles. I'm also adding some new features, I've extended indexing so you can use more complex functions, this supports indexing by sub-attributes, i.e. multiple index entries per record (the use-case was index by "tags": []) and I'm looking to integrate full-text indexing using Xapian and also to release some properly working replication code.

You will be glad to hear it is 100% type annotated :)

It's working but subject to change, the current version sort of evolved over time as project requirements dictated, this time I didn't really want to make it public this time until I'd stopped tweaking it .. but it is usable, let me know if you want to take a look.

**Comment by oddjobz** [comment]
Incidentally, currently the new database format is compatible with the current pynndb model, so it works pretty much with the current pynndb-shell. However, when I get to the C extensions, which may be a little way off just yet, there will be an option to use a new layout which will be between 5-10x faster when used with the extension. (essentially a new form of binary encoding JSON) I wrote a blog post about it here; https://gareth.bult.co.uk/2019/09/16/oy-pack-it-in/

**Comment by oddjobz** [comment]
Ok I've tidied a little, if you're interested the new stuff is public;
https://gitlab.com/oddjobz/pynndb-new

**Comment by rominf** [comment]
Thank you, I'm looking at a new repo now. I liked your old pynndb, the new one looks even better!

**Comment by rominf** [comment]
I want to build GraphDB on top of your pynndb2 for building the library to access conceptnet. I will happy to contribute to your library. I sent you an invitation on LinkedIn.

**Comment by oddjobz** [comment]
Cool!
