### ISSUE TITLE
With how many bytes was the speedtest done?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [oddjobz/pynndb#6]
It says around 40k appends / s but I only get 1k, I'm probably doing something wrong, but wanted to check it is not the obvious that my insertions are just 40times bigger than yours. I insert one timestamp, around 15 ints, 5 strings with around 5-10chars and 2 floats and the table has one index for the timestamp.
This sounds like a lot and I was wondering if the difference in reported speed and observed speed lies in the input or that I use it wrong maybe. I did some benchmarking and the most time is spend in the append method, which makes me think I did things right...

**Comment by oddjobz** [comment]
Hi, can you start by running the original benchmark "as-is" .. this will tell you whether it's an issue with your hardware / system config, or whether you've inadvertently done something in to the code ... ?

**Comment by Kaju-Bubanja** [comment]
I did not see that there was a benchmark. But now I also realized I was still using pymamba(the first line on the Readme page uses pymamba) but the benchmark uses pynndb. So I wasn't using pynndb at all(surprising how stable the api stayed 👍 )
So I tried to install pynndb but now get the infamous `Cannot open include file: 'sys/time.h': No such file or directory` when trying to install the posix_ipc_module.c which is a requirement. Now I was wondering does pynndb even work on Windows?

**Comment by oddjobz** [comment]
Hi, sorry, I'm not 'windows-aware' so I'm afraid I can't help on that one. (I don't actually have a Windows machine [instance / vm / licence] here) That said, you could swap out "time.h" for something else .. what works on Windows, "datetime" ??
